### PR TITLE
Fixes url not loading and locks dependency version

### PR DESCRIPTION
**Pull request by gervasiocaj**

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Thanks, LGTM!

**Comment by MikeRalphson** [comment]
Let me know if you need a new npm release. Thanks again.

**Comment by gervasiocaj** [comment]
Can you update your Heroku app to use the new version? Thanks

**Comment by MikeRalphson** [comment]
Should be updated - but I've not used it in a while. Could you let me know results?

**Pull request merged**
